export const Colors ={
     BUTTON_SIGNIN : "#A25426",
     BUTTON_SIGNUP : "#323232",
     FONT_WHITE: "#FFFFFF",
     SEPARATED_LINE : "#E5E5E5",
     SEPARATED_LINE_TORNUP : "#515151",
     BACKGROUND_DEFAULT : "#FEFCFC",

     REFRIGATOR_AI_BUTTON:"#cb6930",
     SELECTED_ITEM_BACKGROUND : "#ffcc99"
}